# Generated by Django 5.0.4 on 2026-01-01 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('conteudo', models.TextField()),
                ('resumo', models.TextField(blank=True)),
                ('banner_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('data_publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('publicado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEstudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('arquivo_url', models.URLField(verbose_name='Link de Download')),
                ('publicado', models.BooleanField(default=False)),
                ('trimestre', models.CharField(help_text='Ex: 3Tri25', max_length=20)),
                ('licao_numero', models.IntegerField(help_text='Número da lição (1-13)')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.categoria')),
            ],
            options={
                'verbose_name': 'Guia de Estudo',
                'verbose_name_plural': 'Guias de Estudo',
                'ordering': ['-data_publicado'],
            },
        ),
    ]
