# Generated by Django 5.0.4 on 2026-01-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('trimester', models.CharField(max_length=10)),
                ('lesson_number', models.IntegerField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('file_guide', models.FileField(blank=True, null=True, upload_to='bundles/guides/')),
                ('file_slides', models.FileField(blank=True, null=True, upload_to='bundles/slides/')),
                ('file_map', models.FileField(blank=True, null=True, upload_to='bundles/maps/')),
                ('file_infographic', models.FileField(blank=True, null=True, upload_to='bundles/infographics/')),
                ('file_flashcards', models.FileField(blank=True, null=True, upload_to='bundles/flashcards/')),
            ],
        ),
    ]
